In [4]:
#[0]
import numpy as np
from gensim.models.keyedvectors import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.test.utils import datapath, get_tmpfile
import json #https://stackoverflow.com/questions/7100125/storing-python-dictionaries
import pickle #https://stackoverflow.com/questions/11218477/how-can-i-use-pickle-to-save-a-dict
import os
#[1]
from sklearn.manifold import MDS
from scipy.spatial import procrustes
import matplotlib.pyplot as plt

%matplotlib inline

#[2]
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
from sklearn.cluster import DBSCAN

#[3]
from sklearn import decomposition
from scipy.spatial import distance_matrix


from sklearn.manifold import SpectralEmbedding
from sklearn.manifold import Isomap

from mpl_toolkits import mplot3d

In [52]:
emb  = get_emotion_embedding()

In [53]:
dm = distance_matrix(emb,emb)

In [54]:
np.max(dm)

0.40552751127377684

In [61]:
r = np.round(np.array(dm)*10,2)

In [62]:
r

array([[0.  , 2.94, 3.3 , ..., 3.29, 3.26, 2.59],
       [2.94, 0.  , 3.35, ..., 3.25, 2.92, 2.93],
       [3.3 , 3.35, 0.  , ..., 3.47, 3.43, 3.41],
       ...,
       [3.29, 3.25, 3.47, ..., 0.  , 3.48, 3.47],
       [3.26, 2.92, 3.43, ..., 3.48, 0.  , 3.1 ],
       [2.59, 2.93, 3.41, ..., 3.47, 3.1 , 0.  ]])

In [71]:
l = "X "
for s in get_sentiments():
    l+= s + " "
print(l)
for n,i in enumerate(r):
    l = get_sentiments()[n] + " "
    for n_2,j in enumerate(i):
        l += str(j) + " "

    print(l)

X astonished determined serene joyous desperate melancholic amorous condescending distrustful passionate dissatisfied empathic lusting happy miserable indignant jealous amused disgusted hopeful discontented sad insulted distressed tired suspicious contemptuous polite friendly surprise confused peaceful hesitant interested convinced contemplative envious courageous expectant fear impatient delighted annoyed disappointed conceited apathetic satisfied longing attentive content dejected bitter guilt serious confident triumphant worried relaxed startled bored frustrated depressed calm alarmed tense angry embarrassed gloomy despondent impressed enthusiastic wavering ambitious excited 
astonished 0.0 2.94 3.3 3.03 2.97 3.52 3.38 3.17 3.12 3.13 2.84 3.72 3.29 2.77 3.08 2.39 2.93 2.14 2.17 2.89 3.06 2.95 2.84 3.2 2.99 3.03 2.85 3.18 3.33 2.67 2.54 3.67 2.82 2.93 2.48 3.58 2.65 3.27 3.2 3.17 2.81 2.11 2.22 2.36 3.29 3.31 2.73 3.18 3.09 3.62 2.88 3.45 3.71 3.23 2.86 2.94 2.57 3.3 2.0 2.99 2.57 3.

In [40]:
emb*100

[array([-0.00558576,  0.00638577, -0.00435517, ...,  0.00063441,
         0.00575094,  0.0112102 ]),
 array([ 0.00182855,  0.00684911, -0.01119745, ...,  0.00762199,
         0.00415576,  0.00311255]),
 array([-5.54333801e-03, -5.99211773e-03,  7.27495340e-03, ...,
         1.87820196e-02,  8.56149225e-05, -9.94474094e-03]),
 array([-0.01129293,  0.00017106,  0.00275724, ..., -0.00106668,
        -0.00845942, -0.01225522]),
 array([ 0.00745514, -0.00038511,  0.00258112, ..., -0.0041722 ,
         0.0040049 , -0.00714942]),
 array([ 0.00565827, -0.00475005,  0.00959509, ...,  0.01277902,
        -0.00622502,  0.00709548]),
 array([-0.00790181, -0.01007194,  0.00228457, ..., -0.00756431,
         0.00104239,  0.01247897]),
 array([ 0.00013491,  0.00858005,  0.00440155, ..., -0.0011113 ,
        -0.01123408,  0.01373834]),
 array([ 0.00162952,  0.00505673, -0.00784899, ..., -0.00772484,
        -0.01040523, -0.00177069]),
 array([-0.00580716, -0.00788671, -0.00575925, ...,  0.00327015,
  

In [49]:
dm = np.array(emb)
D = dm
n = len(dm)
H = np.eye(n) - np.ones((n, n))/n
B = -H.dot(D**2).dot(H)/2
evals, evecs = np.linalg.eig(B)
idx = np.argsort(evals)[::-1]
evals = evals[idx]
evecs = evecs[:,idx]
w = np.where(evals > 0)
L  = np.diag(np.sqrt(evals[w]))
V  = evecs[:,w]

ValueError: shapes (74,1200) and (74,74) not aligned: 1200 (dim 1) != 74 (dim 0)

In [30]:
idx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35,
       36, 37, 41, 42, 43, 49, 50, 51, 56, 57, 58, 59, 60, 66, 67, 73, 72,
       71, 69, 70, 68, 65, 64, 63, 62, 61, 55, 54, 53, 52, 48, 47, 46, 45,
       44, 40, 39, 38, 31, 17])

In [31]:
for i in idx:
    print(get_sentiments()[i])

astonished
determined
serene
joyous
desperate
melancholic
amorous
condescending
distrustful
passionate
dissatisfied
empathic
lusting
happy
miserable
indignant
jealous
disgusted
hopeful
discontented
sad
insulted
distressed
tired
suspicious
contemptuous
polite
friendly
surprise
confused
hesitant
interested
convinced
contemplative
envious
courageous
delighted
annoyed
disappointed
content
dejected
bitter
worried
relaxed
startled
bored
frustrated
embarrassed
gloomy
excited
ambitious
wavering
impressed
enthusiastic
despondent
angry
tense
alarmed
calm
depressed
triumphant
confident
serious
guilt
attentive
longing
satisfied
apathetic
conceited
impatient
fear
expectant
peaceful
amused


In [3]:
def get_emotion_embedding():
    return get_emb_concat()

def get_final_embs(dimensions = 200):
    embs = get_clean_embeddings()
    embs += [get_emb_soma()]
    embs += [get_emb_concat()]


    mds = MDS(n_components=dimensions)
    #Trata embeddings, filtrando somente os sentimentos principais e colocando no numero minimo de dimensoes
    embeddings = []
    for i in range(len(embs)):
        transformed_embedding = mds.fit_transform(embs[i])
        embeddings += [transformed_embedding]
    embs = embeddings

    for a in range(len(embs)):
        for b in range(len(embs)):
            embs[a],embs[b],r = procrustes(embs[a],embs[b])
    for i in range(200):
        a = np.random.randint(len(embs))
        b = np.random.randint(len(embs))
        embs[a],embs[b],r = procrustes(embs[a],embs[b])
    return embs

def calcula_stress_embeddings(d_original, d_proposta):
    d_original = distance_matrix(d_original,d_original)
    d_proposta = distance_matrix(d_proposta,d_proposta)
    a = np.sum((d_original-d_proposta)**2)
    b = np.sum(d_original**2)
    return np.sqrt(a/b)/4

def calcula_stress(d_original, d_proposta):
    a = np.sum((d_original-d_proposta)**2)
    b = np.sum(d_original**2)
    return np.sqrt(a/b)/4

def get_emb_soma():
    embeddings = get_clean_embeddings()
    sentiments = get_sentiments()
    assemble_embeddings_soma = np.zeros_like(embeddings[0])
    for i in embeddings:
        for c in range(75):
            assemble_embeddings_soma[c] = assemble_embeddings_soma[c] + i[c]
    return assemble_embeddings_soma

def get_emb_concat():
    embeddings = get_clean_embeddings()
    sentiments = get_sentiments()
    assemble_embeddings_concat = []

    for c in range(len(sentiments)):
        tmp = np.array([])
        for i in embeddings:
            tmp = np.concatenate((tmp,i[c]))
        assemble_embeddings_concat += [tmp]
    return assemble_embeddings_concat


def get_emb_media():
    #média dos vetores e retirando outliers
    embeddings = get_clean_embeddings()
    sentiments = get_sentiments()
    assemble_embeddings_media = np.zeros_like(embeddings[0])
    vec = []
    dist = []
    for c in range(75):
        tmp = np.array([])
        vec = []
        for i in embeddings:
            vec += [i[c]]

        centroid = np.zeros_like(vec[0])
        for i in vec:
            centroid = centroid + i
        centroid = centroid/len(vec)

        dist = []
        for i in vec:
            dist += [np.linalg.norm(i-centroid)]

        limitante_distancia_para_corte = np.max(dist)

        counter = 0
        for n,i in enumerate(embeddings):
            if dist[n]!=limitante_distancia_para_corte:
                assemble_embeddings_media[c] += i[c] 
                counter+=1

        assemble_embeddings_media[c] = assemble_embeddings_media[c]/counter
    return assemble_embeddings_media


def get_clean_embeddings():
#Seleciona somente os vetores principais das nossas embeddings
    sentiments = get_sentiments()
    raw_embeddings = []
    dimensions_size = []
    for i in range(4):
        tmp = get_vectors_embedding(i)
        raw_embeddings += [tmp]
        dimensions_size+=[len(get_sentiment_vector(tmp,sentiments[0]))]
#Faz o corte para o menor tamanho de dimensão
    n_dimensions = np.min(dimensions_size)
    # n_dimensions = 10
    mds = MDS(n_components=n_dimensions)
#Trata embeddings, filtrando somente os sentimentos principais e colocando no numero minimo de dimensoes
    embeddings = []
    for i in range(4):
        tmp_embedding = []
        for s in sentiments:
            tmp_embedding += [get_sentiment_vector(raw_embeddings[i],s)]
        transformed_embedding = mds.fit_transform(tmp_embedding)
        embeddings += [transformed_embedding]
    # Calcula erro entre nossos modelos
    for a in range(len(embeddings)):
        for b in range(len(embeddings)):
            embeddings[a],embeddings[b],r = procrustes(embeddings[a],embeddings[b])
    return embeddings

def print_anotado(emb):
    fig, ax = plt.subplots(figsize=(15,15))
    ax.scatter(emb[:,0], emb[:,1])
    n = get_sentiments()
    
    for i, txt in enumerate(n):
        ax.annotate(" "+txt, (emb[:,0][i], emb[:,1][i]))

def print_anotado2(emb):
    fig, ax = plt.subplots(figsize=(15,15))
    for e in emb:
        ax.scatter(e[:,0], e[:,1])
        n = get_sentiments()

        for i, txt in enumerate(n):
            ax.annotate(txt, (e[:,0][i], e[:,1][i]))

def print_2d(embs):
    res = []
    mds_2 = MDS(n_components=2)
    for e in embs:
        res += [mds_2.fit_transform(e)]
    for p in res:
        plt.scatter(p[:,0],p[:,1])

def get_sentiment_vector(embedding, sentiment):
    return embedding[sentiment]["vectors"][sentiment]

def get_vectors_embedding(n):
    files = os.listdir("models")
    model_file_name = []
    for file in files:
        model_file_name += [file]
    escolhidos = [model_file_name[14],model_file_name[5],model_file_name[7],model_file_name[3]]
    with open("models/"+escolhidos[n], 'rb') as handle:
        b = pickle.load(handle)
    return b

def get_sentiments_old():
    sentiments = np.load("./sentiments_list.npy")
    return sentiments
def get_sentiments():
    sentiments = np.load("./sentiments_list.npy")
    sentiments = np.concatenate((sentiments[:26],sentiments[27:]))
    return sentiments